---
# tasks file for ansible-elk

- name: Install Java 8
  include: java.yml

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Kibana
  include: kibana.yml

- name: Install Nginx
  include: nginx.yml

- name: Install Logstash
  include: logstash.yml 
